Repository devsoc-unsw/unilectives, pull requests merged in 2024-06, with the labels that each got.

#282 Feature:UNI/277 Dark Mode Fully Implemented
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/page.tsx
  frontend/src/app/course/[id]/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/terms-and-conditions/page.tsx
  frontend/src/app/user/[zid]/page.tsx
  frontend/src/assets/jane-street-logo.svg
  frontend/src/assets/tiktok-logo.svg
  frontend/src/components/AdminContent/AdminContent.tsx
  frontend/src/components/CollapseMenu/CollapseMenu.tsx
  frontend/src/components/CourseCard/CourseCard.tsx
  frontend/src/components/CoursesList/CoursesList.tsx
  frontend/src/components/DeleteModal/DeleteModal.tsx
  frontend/src/components/DoughnutChart/DoughnutChart.tsx
  frontend/src/components/Dropdown/Dropdown.tsx
  frontend/src/components/EditReviewModal/EditReviewModal.tsx
  frontend/src/components/LandingPageContent/LandingPageContent.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/components/RemoveReviewModal/RemoveReviewModal.tsx
  frontend/src/components/ReportCard/ReportCard.tsx
  frontend/src/components/ReviewCard/ReviewCard.tsx
  frontend/src/components/ReviewModal/ReviewModal.tsx
  frontend/src/components/SearchBar/SearchBar.tsx
  frontend/src/components/ThemeComponents/ThemeProvider.tsx
  frontend/src/components/ThemeComponents/ThemeSwitcher.tsx
  frontend/src/components/Tooltip/Tooltip.tsx
  frontend/src/components/UserBookmarkedReviews/UserBookmarkedReviews.tsx
  frontend/src/components/UserPageContent/UserPageContent.tsx
  frontend/src/components/UserReports/UserReports.tsx
  frontend/src/components/UserReviews/UserReviews.tsx
  frontend/tailwind.config.js
Labels: enhancement

#299 Feature:UNI/277 Dark Mode fix for flashing
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/components/ThemeComponents/ThemeProvider.tsx
  frontend/src/components/ThemeComponents/ThemeSwitcher.tsx
Labels: bug

#300 feature: UNI/277: Dark Mode Flashing when content is not mounted
  frontend/src/app/layout.tsx
  frontend/src/app/user/[zid]/page.tsx
  frontend/src/components/ThemeComponents/ThemeProvider.tsx
  frontend/src/components/ThemeComponents/ThemeSwitcher.tsx
Labels: bug, enhancement

#295 chore: UNI-292 linting GitHub actions
  .github/workflows/ci.yml
  backend/package.json
  frontend/package.json
  migration/package.json
  migration/src/migrate/index.ts
  migration/src/migrate/repository.ts
  migration/src/migrate/service.ts
Labels: github_actions
